# for arm based processers
---
apiVersion: v1
kind: Secret
metadata:
  name: mongo-credentials
type: Opaque
data:
  MONGO_USER: Y2hhaXRhbnlhCg==  # base64-encoded value of "chaitu"
  MONGO_PASSWORD: MTIzQ2hhaXR1  # base64-encoded value of "123Chaitu"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spec-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spec
  template:
    metadata:
      labels:
        app: spec
    spec:
      containers:
      - name: spec
        image: chaituchowdary/app:arm64_latest
        env:
        - name: MONGO_USER
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: MONGO_USER
        - name: MONGO_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-credentials
              key: MONGO_PASSWORD
        - name: MONGO_ENDPOINT
          value: "mongodb+srv://$(MONGO_USER):$(MONGO_PASSWORD)@chaitanya.kj7ag4f.mongodb.net/login-app-db?retryWrites=true&w=majority"
        - name: ENV
          value: "dev"
        - name: APP_VERSION
          value: "5.0"
        - name: PORT
          value: "8800"

---

apiVersion: v1
kind: Service
metadata:
  name: spec-service
spec:
  selector:
    app: spec
  ports:
  - protocol: TCP
    port: 9000 # Exposes port 9000 externally
    targetPort: 8800
  type: LoadBalancer
